apiVersion: tempo.grafana.com/v1alpha1
kind:  TempoStack
metadata:
  name: platform
  namespace: openshift-tracing
spec:
  storage:
    secret:
      name: observability-demo-tempo-secret
      type: s3
    tls:
      caName: "openshift-service-ca.crt"
      caKey: "service-ca.crt"
  storageSize: 1Gi
  resources:
    total:
      limits:
        memory: 8Gi
        cpu: 4000m
  tenants:
    mode: openshift
    authentication:
      - tenantName: platform
        tenantId: "1610b0c3-c509-4592-a256-a1871353dbfa"
  template:
    gateway:
      enabled: true
    querier:
      replicas: 1
      resources:
        limits:
          memory: 2Gi
          cpu: "2"
    queryFrontend:
      component:
        replicas: 1
        resources:
          limits:
            memory: 2Gi
            cpu: "2"
