apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: myreadings-app
  namespace: myreadings-dev
  labels:
    app.kubernetes.io/part-of: myreadings
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: myreadings-app
  endpoints:
    - port: http
      path: /q/metrics
      interval: 15s
